### ISSUE TITLE
Allow use with Symfony 6 LTS

### ISSUE THREAD

**Issue by FlyingDR** [Intervention/image-symfony#2]
Currently, the bundle requires Symfony 7 as a minimum:

https://github.com/Intervention/image-symfony/blob/ae559037c43d05023b45944068978caa63df3212/composer.json#L26

Symfony 6.4 is an LTS release that will be supported [until November 2027](https://symfony.com/releases/6.4). Due to [Backward Compatibility](https://symfony.com/doc/current/contributing/community/releases.html#backward-compatibility) promise the only difference between 6.4 and 7.0 is the removal of the deprecated code in 7.0.

I would want to ask you to allow using your bundle with Symfony 6 LTS by changing requirement string to `^6.4|^7`

**Comment by olivervogel** [comment]
My knowledge of Symfony is unfortunately somewhat limited. Is it possible to use `6.4` by simply changing the version number like you suggested or do further adjustments have to be done?

If it is only a matter of adjusting the version number, you are welcome to submit this as a merge request.

**Comment by FlyingDR** [comment]
> My knowledge of Symfony is unfortunately somewhat limited. Is it possible to use `6.4` by simply changing the version number like you suggested or do further adjustments have to be done?

@olivervogel Yes, as I wrote before - versions 6.4 and 7.0 are actually the same code with the only difference being that 7.0 removes all features that are marked as deprecated in 6.x.

The bundle itself is currently very simple and the dependency injection component is relatively stable so nothing should go wrong.
 
> If it is only a matter of adjusting the version number, you are welcome to submit this as a merge request.

Pull request is added: https://github.com/FlyingDR/image-symfony/pull/1

**Comment by olivervogel** [comment]
Thanks. This is now included in `1.0.2`.
